---
kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ulrichschreiner/ansible
    auto_tag: true
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password
