---
kind: pipeline
type: docker
name: default

steps:
- name: tag
  image: registry.gitlab.com/ulrichschreiner/go-web-dev
  commands:
    - git fetch --tags
    - echo "latest,$(git describe --abbrev=0)" >.tags

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ulrichschreiner/ansible
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password
