#!/bin/sh

_ansible() {
  subc=$1
  if [ "$#" -gt 0 ]; then
    shift
  else
    subc=--help
  fi
  if [ "x$ANSIBLE_VAULT_PASSWORD_FILE" = "x" ]; then
    docker run -it --rm \
      --net host \
      -v $SSH_AUTH_SOCK:/ssh-agent \
      --env SSH_AUTH_SOCK=/ssh-agent \
      -v `pwd`:/work \
      -v ${ANSIBLE_CONFIG_DIR:-/etc/ansible}:/etc/ansible \
      ulrichschreiner/ansible $subc "$@"
  else
    docker run -it --rm \
      --net host \
      -v $SSH_AUTH_SOCK:/ssh-agent \
      --env SSH_AUTH_SOCK=/ssh-agent \
      --env ANSIBLE_VAULT_PASSWORD_FILE=$ANSIBLE_VAULT_PASSWORD_FILE \
      -v `pwd`:/work \
      -v ${ANSIBLE_CONFIG_DIR:-/etc/ansible}:/etc/ansible \
      -v ${ANSIBLE_VAULT_PASSWORD_FILE}:${ANSIBLE_VAULT_PASSWORD_FILE} \
      ulrichschreiner/ansible $subc "$@"
  fi
}

PROG=`basename $0`

case "$PROG" in
   "ansible") _ansible -u `whoami` "$@"
   ;;
   "ansible-playbook") _ansible playbook -u `whoami` "$@"
   ;;
   "ansible-vault") _ansible vault "$@"
   ;;
   "ansible-doc") _ansible doc "$@"
   ;;
   "ansible-pull") _ansible pull -u `whoami` "$@"
   ;;
   "ansible-galaxy") _ansible galaxy "$@"
   ;;
   "ansible-config") _ansible config "$@"
   ;;
   "ansible-console") _ansible console -u `whoami` "$@"
   ;;
   "ansible-inventory") _ansible inventory "$@"
   ;;
esac
